import type { ComponentProps } from 'react'
import {
  Activity,
  Award,
  BadgeCheck,
  Bell,
  Book,
  Bookmark,
  BookOpen,
  Briefcase,
  Building,
  Building2,
  Calculator,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  Clock,
  Cloud,
  Code,
  Cog,
  Compass,
  Cpu,
  CreditCard,
  Database,
  Download,
  ExternalLink,
  File,
  FileText,
  Flag,
  Folder,
  Globe,
  GraduationCap,
  Grid,
  HandCoins,
  Heart,
  HeartPulse,
  HelpCircle,
  Image,
  Info,
  Key,
  Laptop,
  Layers,
  Layout,
  Library,
  List,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  Monitor,
  Music,
  Newspaper,
  Palette,
  Paperclip,
  Phone,
  Printer,
  School,
  Search,
  Send,
  Server,
  Share2,
  Shield,
  ShieldCheck,
  Sliders,
  Sparkles,
  Star,
  Tag,
  Terminal,
  ThumbsUp,
  Trophy,
  Truck,
  Umbrella,
  User,
  UserCheck,
  Users,
  Video,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react'

const iconDictionary: Record<string, LucideIcon> = {
  // Common service icons
  database: Database,
  server: Server,
  cpu: Cpu,
  cloud: Cloud,
  code: Code,
  laptop: Laptop,
  monitor: Monitor,
  terminal: Terminal,
  school: School,
  'graduation-cap': GraduationCap,
  'book-open': BookOpen,
  book: Book,
  building: Building,
  'building-2': Building2,
  library: Library,
  award: Award,
  trophy: Trophy,
  shield: Shield,
  'shield-check': ShieldCheck,
  'user-check': UserCheck,
  users: Users,
  user: User,
  activity: Activity,
  'heart-pulse': HeartPulse,
  heart: Heart,
  'map-pin': MapPin,
  phone: Phone,
  mail: Mail,
  globe: Globe,
  folder: Folder,
  file: File,
  'file-text': FileText,
  'badge-check': BadgeCheck,
  calendar: Calendar,
  'hand-coins': HandCoins,
  newspaper: Newspaper,
  download: Download,
  sparkles: Sparkles,
  search: Search,
  lock: Lock,
  key: Key,
  cog: Cog,
  settings: Cog,
  'help-circle': HelpCircle,
  info: Info,
  'check-circle': CheckCircle,
  'share-2': Share2,
  'external-link': ExternalLink,
  music: Music,
  camera: Camera,
  video: Video,
  image: Image,
  palette: Palette,
  compass: Compass,
  flag: Flag,
  bookmark: Bookmark,
  layers: Layers,
  grid: Grid,
  layout: Layout,
  list: List,
  check: Check,
  star: Star,
  zap: Zap,
  bell: Bell,
  briefcase: Briefcase,
  calculator: Calculator,
  clock: Clock,
  'credit-card': CreditCard,
  paperclip: Paperclip,
  printer: Printer,
  send: Send,
  sliders: Sliders,
  tag: Tag,
  'thumbs-up': ThumbsUp,
  truck: Truck,
  umbrella: Umbrella,
  wifi: Wifi,
  wrench: Wrench,
  'message-circle': MessageCircle,
}

export function getLucideIcon(name?: string | null): LucideIcon {
  if (!name) return Sparkles

  const cleanName = name.trim().toLowerCase().replace(/_/g, '-')
  if (iconDictionary[cleanName]) {
    return iconDictionary[cleanName]
  }

  // Fallback: hapus strip
  const noDash = cleanName.replace(/-/g, '')
  for (const key of Object.keys(iconDictionary)) {
    if (key.replace(/-/g, '') === noDash) {
      return iconDictionary[key]
    }
  }

  return Sparkles
}

type DynamicIconProps = {
  name?: string | null
} & LucideProps

export function DynamicIcon({ name, ...props }: DynamicIconProps) {
  const Icon = getLucideIcon(name)
  return <Icon {...props} />
}

export default DynamicIcon
