# docker-compose override untuk PRODUCTION — pakai image dari Docker Hub
# Usage: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d
services:
  frontend:
    image: ardianryan/b68b687bb88by7ybby7fwbbf8eb7b8y3:frontend-latest
    build: !reset null

  backend:
    image: ardianryan/b68b687bb88by7ybby7fwbbf8eb7b8y3:backend-latest
    build: !reset null
